background: "thinkpad.jpg"
language: "en-GB"
logo: "benjamin-edward-howe.svg"
tagline: "Software Engineer"
title: "Benjamin Howe"

plugins:
  - jekyll/minibundle

exclude:
  - netlify.toml
  - README.md
