language: "en-GB"
logo: "beh.svg"
permalink: /:year/:title
tagline: "Software Engineer"
title: "Benjamin Edward Howe"
author: "Benjamin Howe"

plugins:
  - jekyll-feed
  - jekyll/minibundle

include:
  - _redirects

exclude:
  - functions
  - README.md

minibundle:
  minifier_commands:
    css: cat # TODO: replace this with a proper minifier
