url: "https://jekyll-blank.beh.uk/" # the base hostname & protocol for your site, e.g. http://example.com
title: "Blank Jekyll Site" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll/minibundle

exclude:
  - netlify.toml
  - README.md
