language: "en-GB"
logo: "beh.svg"
permalink: /:year/:title:output_ext
tagline: "Software Engineer"
title: "Benjamin Edward Howe"

plugins:
  - jekyll/minibundle

exclude:
  - netlify.toml
  - README.md
