[build]
  command = 'npm install uglifycss && jekyll build'
  publish = "_site"

[context.branch-deploy]
  command = 'npm install uglifycss && jekyll build --drafts --future'

[build.environment]
  JEKYLL_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=63072000"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
